### ISSUE TITLE
一些关于docker的问题

### ISSUE THREAD

**Issue by Godthumb** [YaoZhang93/FLARE2021-Baseline#11]
您好，我这边打包docker遇到一些问题。docker 已经可以正常打包了。但是在加载打包好的image验证的时候，会报错。
ValueError: 'ImportError: libSM.so.6: cannot open shared object file: No such file or directorylayer4_3' is not a valid scope name
。一下是我的dockerfile
# 基于镜像基础
# FROM python:3.6
FROM tensorflow/tensorflow:1.14.0-gpu-py3

RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list  && \
    sed -i s@/security.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
# 设置代码文件夹工作目录 /app
WORKDIR /app
  
 # 复制当前代码文件到容器中 /app
ADD . /app

RUN apt-get update
RUN apt-get install -y libsm6 libxext6 libxrender-dev 

 # 安装所需的包
RUN pip install --no-index --find-links=./pip_packages -r requirements.txt
RUN pip install  ./pip_packages/astropy-1.2.1-cp36-cp36m-linux_x86_64.whl
RUN pip install ./pip_packages/cffi-1.7.0-cp36-cp36m-linux_x86_64.whl
RUN pip install ./pip_packages/cryptography-1.5-cp36-cp36m-linux_x86_64.whl
RUN pip install ./pip_packages/numba-0.28.1-cp36-cp36m-linux_x86_64.whl
RUN pip install ./pip_packages/scikit_learn-0.17.1-cp36-cp36m-linux_x86_64.whl
RUN pip install ./pip_packages/lxml-3.6.4-cp36-cp36m-linux_x86_64.whl
 # Run app.py when the container launches
CMD ["sh", "predict.sh"]

**Comment by JunMa11** [comment]
Please list the building log.

It seems that some packages are not correctly installed.

**Comment by Godthumb** [comment]
1.14.0-gpu-py3: Pulling from tensorflow/tensorflow
Digest: sha256:e72e66b3dcb9c9e8f4e5703965ae1466b23fe8cad59e1c92c6e9fa58f8d81dc8
Status: Downloaded newer image for tensorflow/tensorflow:1.14.0-gpu-py3
 ---> a7a1861d2150
Step 2/14 : RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list  &&     sed -i s@/security.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
 ---> Running in fae9918587ce
Removing intermediate container fae9918587ce
 ---> 82d0f498d4c2
Step 3/14 : WORKDIR /app
 ---> Running in 50833b8784a4
Removing intermediate container 50833b8784a4
 ---> 4532d3614e7b
Step 4/14 : ADD . /app
 ---> 0df42f315bfc
Step 5/14 : RUN apt-get update
 ---> Running in 7f4e38a8d729
Get:1 file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda10.0  InRelease
Ign:1 file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda10.0  InRelease
Get:2 file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda10.0  Release [574 B]
Get:2 file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda10.0  Release [574 B]
Get:3 http://mirrors.aliyun.com/ubuntu bionic InRelease [242 kB]
Get:5 http://mirrors.aliyun.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:6 http://mirrors.aliyun.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:8 http://mirrors.aliyun.com/ubuntu bionic-security InRelease [88.7 kB]
Get:10 http://mirrors.aliyun.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:11 http://mirrors.aliyun.com/ubuntu bionic/main amd64 Packages [1344 kB]
Ign:7 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Ign:9 https://developer.download.nvidia.cn/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:12 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64  Release [697 B]
Get:13 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg [836 B]
Get:14 https://developer.download.nvidia.cn/compute/machine-learning/repos/ubuntu1804/x86_64  Release [564 B]
Ign:15 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64  Packages
Get:16 https://developer.download.nvidia.cn/compute/machine-learning/repos/ubuntu1804/x86_64  Release.gpg [833 B]
Ign:15 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages
Get:17 https://developer.download.nvidia.cn/compute/machine-learning/repos/ubuntu1804/x86_64  Packages [73.8 kB]
Get:15 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64  Packages [695 kB]
Get:18 http://mirrors.aliyun.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:19 http://mirrors.aliyun.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:20 http://mirrors.aliyun.com/ubuntu bionic-updates/multiverse amd64 Packages [39.5 kB]
Get:21 http://mirrors.aliyun.com/ubuntu bionic-updates/restricted amd64 Packages [537 kB]
Get:22 http://mirrors.aliyun.com/ubuntu bionic-updates/main amd64 Packages [2694 kB]
Get:23 http://mirrors.aliyun.com/ubuntu bionic-updates/universe amd64 Packages [2194 kB]
Get:24 http://mirrors.aliyun.com/ubuntu bionic-backports/main amd64 Packages [11.3 kB]
Get:25 http://mirrors.aliyun.com/ubuntu bionic-backports/universe amd64 Packages [11.4 kB]
Get:26 http://mirrors.aliyun.com/ubuntu bionic-security/restricted amd64 Packages [505 kB]
Get:27 http://mirrors.aliyun.com/ubuntu bionic-security/main amd64 Packages [2258 kB]
Get:28 http://mirrors.aliyun.com/ubuntu bionic-security/universe amd64 Packages [1420 kB]
Get:29 http://mirrors.aliyun.com/ubuntu bionic-security/multiverse amd64 Packages [26.7 kB]
Fetched 23.8 MB in 40s (600 kB/s)
Reading package lists...
Removing intermediate container 7f4e38a8d729
 ---> 2751dd329cbb
Step 6/14 : RUN apt-get install -y libsm6 libxext6 libxrender-dev
 ---> Running in 3affbe9a8313
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libbsd0 libice6 libpthread-stubs0-dev libx11-6 libx11-data libx11-dev
  libx11-doc libxau-dev libxau6 libxcb1 libxcb1-dev libxdmcp-dev libxdmcp6
  libxrender1 x11-common x11proto-core-dev x11proto-dev xorg-sgml-doctools
  xtrans-dev
Suggested packages:
  libxcb-doc
The following NEW packages will be installed:
  libbsd0 libice6 libpthread-stubs0-dev libsm6 libx11-6 libx11-data libx11-dev
  libx11-doc libxau-dev libxau6 libxcb1 libxcb1-dev libxdmcp-dev libxdmcp6
  libxext6 libxrender-dev libxrender1 x11-common x11proto-core-dev
  x11proto-dev xorg-sgml-doctools xtrans-dev
0 upgraded, 22 newly installed, 0 to remove and 143 not upgraded.
Need to get 4104 kB of archives.
After this operation, 19.9 MB of additional disk space will be used.
Get:1 http://mirrors.aliyun.com/ubuntu bionic-updates/main amd64 libxau6 amd64 1:1.0.8-1ubuntu1 [7556 B]
Get:2 http://mirrors.aliyun.com/ubuntu bionic-updates/main amd64 libbsd0 amd64 0.8.7-1ubuntu0.1 [41.6 kB]
Get:3 http://mirrors.aliyun.com/ubuntu bionic/main amd64 libxdmcp6 amd64 1:1.1.2-3 [10.7 kB]
Get:4 http://mirrors.aliyun.com/ubuntu bionic-updates/main amd64 libxcb1 amd64 1.13-2~ubuntu18.04 [45.5 kB]
Get:5 http://mirrors.aliyun.com/ubuntu bionic-updates/main amd64 libx11-data all 2:1.6.4-3ubuntu0.4 [114 kB]
Get:6 http://mirrors.aliyun.com/ubuntu bionic-updates/main amd64 libx11-6 amd64 2:1.6.4-3ubuntu0.4 [572 kB]
Get:7 http://mirrors.aliyun.com/ubuntu bionic/main amd64 libxext6 amd64 2:1.3.3-1 [29.4 kB]
Get:8 http://mirrors.aliyun.com/ubuntu bionic-updates/main amd64 x11-common all 1:7.7+19ubuntu7.1 [22.5 kB]
Get:9 http://mirrors.aliyun.com/ubuntu bionic/main amd64 libice6 amd64 2:1.0.9-2 [40.2 kB]
Get:10 http://mirrors.aliyun.com/ubuntu bionic/main amd64 libsm6 amd64 2:1.2.2-1 [15.8 kB]
Get:11 http://mirrors.aliyun.com/ubuntu bionic/main amd64 libpthread-stubs0-dev amd64 0.3-4 [4068 B]
Get:12 http://mirrors.aliyun.com/ubuntu bionic/main amd64 xorg-sgml-doctools all 1:1.11-1 [12.9 kB]
Get:13 http://mirrors.aliyun.com/ubuntu bionic/main amd64 x11proto-dev all 2018.4-4 [251 kB]
Get:14 http://mirrors.aliyun.com/ubuntu bionic/main amd64 x11proto-core-dev all 2018.4-4 [2620 B]
Get:15 http://mirrors.aliyun.com/ubuntu bionic-updates/main amd64 libxau-dev amd64 1:1.0.8-1ubuntu1 [9476 B]
Get:16 http://mirrors.aliyun.com/ubuntu bionic/main amd64 libxdmcp-dev amd64 1:1.1.2-3 [25.1 kB]
Get:17 http://mirrors.aliyun.com/ubuntu bionic/main amd64 xtrans-dev all 1.3.5-1 [70.5 kB]
Get:18 http://mirrors.aliyun.com/ubuntu bionic-updates/main amd64 libxcb1-dev amd64 1.13-2~ubuntu18.04 [80.0 kB]
Get:19 http://mirrors.aliyun.com/ubuntu bionic-updates/main amd64 libx11-dev amd64 2:1.6.4-3ubuntu0.4 [641 kB]
Get:20 http://mirrors.aliyun.com/ubuntu bionic-updates/main amd64 libx11-doc all 2:1.6.4-3ubuntu0.4 [2065 kB]
Get:21 http://mirrors.aliyun.com/ubuntu bionic/main amd64 libxrender1 amd64 1:0.9.10-1 [18.7 kB]
Get:22 http://mirrors.aliyun.com/ubuntu bionic/main amd64 libxrender-dev amd64 1:0.9.10-1 [24.9 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 4104 kB in 9s (477 kB/s)
Selecting previously unselected package libxau6:amd64.
(Reading database ... 15404 files and directories currently installed.)
Preparing to unpack .../00-libxau6_1%3a1.0.8-1ubuntu1_amd64.deb ...
Unpacking libxau6:amd64 (1:1.0.8-1ubuntu1) ...
Selecting previously unselected package libbsd0:amd64.
Preparing to unpack .../01-libbsd0_0.8.7-1ubuntu0.1_amd64.deb ...
Unpacking libbsd0:amd64 (0.8.7-1ubuntu0.1) ...
Selecting previously unselected package libxdmcp6:amd64.
Preparing to unpack .../02-libxdmcp6_1%3a1.1.2-3_amd64.deb ...
Unpacking libxdmcp6:amd64 (1:1.1.2-3) ...
Selecting previously unselected package libxcb1:amd64.
Preparing to unpack .../03-libxcb1_1.13-2~ubuntu18.04_amd64.deb ...
Unpacking libxcb1:amd64 (1.13-2~ubuntu18.04) ...
Selecting previously unselected package libx11-data.
Preparing to unpack .../04-libx11-data_2%3a1.6.4-3ubuntu0.4_all.deb ...
Unpacking libx11-data (2:1.6.4-3ubuntu0.4) ...
Selecting previously unselected package libx11-6:amd64.
Preparing to unpack .../05-libx11-6_2%3a1.6.4-3ubuntu0.4_amd64.deb ...
Unpacking libx11-6:amd64 (2:1.6.4-3ubuntu0.4) ...
Selecting previously unselected package libxext6:amd64.
Preparing to unpack .../06-libxext6_2%3a1.3.3-1_amd64.deb ...
Unpacking libxext6:amd64 (2:1.3.3-1) ...
Selecting previously unselected package x11-common.
Preparing to unpack .../07-x11-common_1%3a7.7+19ubuntu7.1_all.deb ...
dpkg-query: no packages found matching nux-tools
Unpacking x11-common (1:7.7+19ubuntu7.1) ...
Selecting previously unselected package libice6:amd64.
Preparing to unpack .../08-libice6_2%3a1.0.9-2_amd64.deb ...
Unpacking libice6:amd64 (2:1.0.9-2) ...
Selecting previously unselected package libsm6:amd64.
Preparing to unpack .../09-libsm6_2%3a1.2.2-1_amd64.deb ...
Unpacking libsm6:amd64 (2:1.2.2-1) ...
Selecting previously unselected package libpthread-stubs0-dev:amd64.
Preparing to unpack .../10-libpthread-stubs0-dev_0.3-4_amd64.deb ...
Unpacking libpthread-stubs0-dev:amd64 (0.3-4) ...
Selecting previously unselected package xorg-sgml-doctools.
Preparing to unpack .../11-xorg-sgml-doctools_1%3a1.11-1_all.deb ...
Unpacking xorg-sgml-doctools (1:1.11-1) ...
Selecting previously unselected package x11proto-dev.
Preparing to unpack .../12-x11proto-dev_2018.4-4_all.deb ...
Unpacking x11proto-dev (2018.4-4) ...
Selecting previously unselected package x11proto-core-dev.
Preparing to unpack .../13-x11proto-core-dev_2018.4-4_all.deb ...
Unpacking x11proto-core-dev (2018.4-4) ...
Selecting previously unselected package libxau-dev:amd64.
Preparing to unpack .../14-libxau-dev_1%3a1.0.8-1ubuntu1_amd64.deb ...
Unpacking libxau-dev:amd64 (1:1.0.8-1ubuntu1) ...
Selecting previously unselected package libxdmcp-dev:amd64.
Preparing to unpack .../15-libxdmcp-dev_1%3a1.1.2-3_amd64.deb ...
Unpacking libxdmcp-dev:amd64 (1:1.1.2-3) ...
Selecting previously unselected package xtrans-dev.
Preparing to unpack .../16-xtrans-dev_1.3.5-1_all.deb ...
Unpacking xtrans-dev (1.3.5-1) ...
Selecting previously unselected package libxcb1-dev:amd64.
Preparing to unpack .../17-libxcb1-dev_1.13-2~ubuntu18.04_amd64.deb ...
Unpacking libxcb1-dev:amd64 (1.13-2~ubuntu18.04) ...
Selecting previously unselected package libx11-dev:amd64.
Preparing to unpack .../18-libx11-dev_2%3a1.6.4-3ubuntu0.4_amd64.deb ...
Unpacking libx11-dev:amd64 (2:1.6.4-3ubuntu0.4) ...
Selecting previously unselected package libx11-doc.
Preparing to unpack .../19-libx11-doc_2%3a1.6.4-3ubuntu0.4_all.deb ...
Unpacking libx11-doc (2:1.6.4-3ubuntu0.4) ...
Selecting previously unselected package libxrender1:amd64.
Preparing to unpack .../20-libxrender1_1%3a0.9.10-1_amd64.deb ...
Unpacking libxrender1:amd64 (1:0.9.10-1) ...
Selecting previously unselected package libxrender-dev:amd64.
Preparing to unpack .../21-libxrender-dev_1%3a0.9.10-1_amd64.deb ...
Unpacking libxrender-dev:amd64 (1:0.9.10-1) ...
Setting up libpthread-stubs0-dev:amd64 (0.3-4) ...
Setting up xorg-sgml-doctools (1:1.11-1) ...
Setting up libbsd0:amd64 (0.8.7-1ubuntu0.1) ...
Setting up x11proto-dev (2018.4-4) ...
Setting up xtrans-dev (1.3.5-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Setting up libx11-doc (2:1.6.4-3ubuntu0.4) ...
Setting up libxdmcp6:amd64 (1:1.1.2-3) ...
Setting up x11-common (1:7.7+19ubuntu7.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up libx11-data (2:1.6.4-3ubuntu0.4) ...
Setting up libxau6:amd64 (1:1.0.8-1ubuntu1) ...
Setting up x11proto-core-dev (2018.4-4) ...
Setting up libxau-dev:amd64 (1:1.0.8-1ubuntu1) ...
Setting up libxdmcp-dev:amd64 (1:1.1.2-3) ...
Setting up libice6:amd64 (2:1.0.9-2) ...
Setting up libxcb1:amd64 (1.13-2~ubuntu18.04) ...
Setting up libsm6:amd64 (2:1.2.2-1) ...
Setting up libx11-6:amd64 (2:1.6.4-3ubuntu0.4) ...
Setting up libxrender1:amd64 (1:0.9.10-1) ...
Setting up libxcb1-dev:amd64 (1.13-2~ubuntu18.04) ...
Setting up libx11-dev:amd64 (2:1.6.4-3ubuntu0.4) ...
Setting up libxext6:amd64 (2:1.3.3-1) ...
Setting up libxrender-dev:amd64 (1:0.9.10-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Removing intermediate container 3affbe9a8313
 ---> f73ecaeb3de4

**Comment by anxingle** [comment]
Could you show more context about the error?

**Comment by Godthumb** [comment]
Traceback (most recent call last):
  File "app.py", line 99, in <module>
    inferencewithsize()
  File "app.py", line 49, in inferencewithsize
    model_path="log\step1\categorical_focal_losss\model\Vnet3d.pd")
  File "/app/Vnet_mutil/model_vnet3d.py", line 53, in __init__
    self.numclass)
  File "/app/Vnet_mutil/networks.py", line 129, in _create_conv_net
    scope='ImportError: libSM.so.6: cannot open shared object file: No such file or directorylayer4_3')
  File "/app/Vnet_mutil/networks.py", line 7, in conv_bn_relu_drop
    with tf.name_scope(scope):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6513, in __enter__
    return self._name_scope.__enter__()
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 4312, in name_scope
    raise ValueError("'%s' is not a valid scope name" % name)
ValueError: 'ImportError: libSM.so.6: cannot open shared object file: No such file or directorylayer4_3' is not a valid scope name

**Comment by anxingle** [comment]
what is your script of run the docker container?

**Comment by Godthumb** [comment]
docker contariner run --name deeplearn --rm -v $PWD/inputs -v $PWD/outputs/ deeplearn:latest /bin/bash/ -c "sh predict.sh"

**Comment by anxingle** [comment]
It seems that your docker image is out of date. **tensorflow:1.14.0-gpu-py3** is a very old version and there are no updates for this, can you please upgrade yo a later version and see if you face any issues.

**Comment by Godthumb** [comment]
您好，我想问下，现在我的docker在cpu环境下可以正常使用，推理正常，但是使用命令'--gpu'运行报错，无法在gpu环境运行，要怎么解决，错误如下：
Error response from daemon :could not select device driver "" with capabilities :  [[gpu]]

**Comment by JunMa11** [comment]
@Godthumb 没有安装nvidia docker

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/overview.html

**Comment by Godthumb** [comment]
thank u.the problem has been solved by install nvidia docker.
